import { Article } from '../types';

export const initialArticles: Article[] = [
  {
    id: 'art-1',
    title: 'The Cognitive Architecture of "Slope": Space, Velocity, and Neural Adaptation',
    subtitle: 'Generated by DeepMind-G v1.5 • Scientific Analysis',
    content: `### 1. The Spatial Processing Loop
When a human player engages with the fast-paced geometric simulation known as *Slope*, their visual cortex experiences a highly concentrated stream of high-frequency spatial vectors. The primary task—steering a sphere down a neon three-dimensional terminal path of variable steepness—requires real-time anticipation of gravitational offsets and kinetic alignment.

Research in computer-human interaction shows that:
* **Saccade acceleration** increases by up to 130% as the ball speeds up.
* **Motor cortical preparation** occurs in under 180 milliseconds, exceeding general physical reflex benchmarks.
* The brain maps the neon green hazards as high-priority negative rewards, triggering a steady micro-dose of dopamine with each second of survival.

### 2. Synaptic Plasticity and Kinetic Calibration
Unlike static puzzle systems, *Slope* demands dynamic kinetic adaptation. Because the rate of acceleration is non-linear, players cannot rely on fixed-interval tapping. Instead, they must develop a "fluid tracking model," calibrating their key presses to the scale of visual compression on the screen. This promotes lateral cognitive flexibility and improves visual-motor coordination under sudden structural shifts.`,
    date: 'Jun 04, 2026',
    category: 'Cognitive Science',
    readTime: '3 min read'
  },
  {
    id: 'art-2',
    title: 'Decoding the 2048 Paradox: Mathematical Induction and Strategic Grid Management',
    subtitle: 'Generated by DeepMind-G v1.5 • Algebraic Game Theory',
    content: `### 1. The Powers of Two and Modular Space
The legendary game *2048* presents a deceptively simplistic $4\\times4$ play space governed by simple binary arithmetic. However, beneath this minimalism lies a rigorous exercise in mathematical induction and algorithmic search.

To model optimal behavior, AI solvers conceptualize the grid as an array of numerical weights where the corner boundary functions as a sink. Placing the highest value tile in a stable corner (e.g., Row 4, Col 4) minimizes structural entropy:
1. **Mono-directional folding:** Restricting valid swipe moves to only two adjacent axes (such as Down and Right) prevents low-value inserts from interrupting strategic rows.
2. **Gradient ordering:** Arranging tiles in a descending sequence around the corner sink allows cascading combinations to trigger in a single movement.

### 2. Probability and the Random Insert Risk
Each turn carries a 10% risk of spawning a "4" tile instead of a "2." This insertion serves as random noise, frustrating linear planning. When the grid reaches 85% density, single-step mistakes run a high chance of resulting in gridlocks. Thus, *2048* is fundamentally a game of risk-aversion, training players to prioritize spatial compressibility above immediate score gains.`,
    date: 'May 28, 2026',
    category: 'Mathematics',
    readTime: '4 min read'
  },
  {
    id: 'art-3',
    title: 'Cyber-Stealth & Proxy Ecosystems: Navigating the Decentralized Classroom Web',
    subtitle: 'Generated by DeepMind-G v1.5 • Informational Sovereignty',
    content: `### 1. The Cat-and-Mouse Game of Network Filters
Within modern educational institutions, network administrators implement rigid content-filtering appliances to restrict access to non-academic nodes. However, this centralized protocol has led to an interesting counter-response: the rise of highly optimized proxy networks, SSH tunnels, and nested mirror sites.

The mechanisms driving block-evasion are highly collaborative:
* **Dynamic Domain Rotation:** Re-routing requests through cloud server networks makes standard DNS-blocking ineffective.
* **Encrypted WebSocket Pipes:** Disguising data streams as innocent HTTPS web traffic hides game payloads from stateful packet inspections.
* **Mirrored Web Repositories:** Storing game elements on open-ended repository websites ensures static blockers cannot catch them all.

### 2. Pedagogical Implications of Unblocked Tech
While filters aim to maximize focus, they sometimes stifle a student's natural curiosity for network engineering. Adapting to network conditions to secure gaming portals or custom proxies serves as an excellent introduction to network protocols, DNS resolution, and security engineering.`,
    date: 'May 15, 2026',
    category: 'Network Security',
    readTime: '5 min read'
  }
];

// Interactive generation templates for hilarious on-the-fly AI articles
export const gameOptions = [
  { value: 'Slope', label: 'Slope Speedrunner' },
  { value: '2048', label: '2048 Binary Solver' },
  { value: 'Retro Bowl', label: 'Retro Bowl Pixel Coach' },
  { value: 'Tunnel Rush', label: 'Tunnel Rush Reflexes' },
  { value: 'Proxy Tech', label: 'Proxy Bypass Network' },
  { value: 'Chat AI', label: 'Socio-Neural Chatbots' }
];

export const toneOptions = [
  { value: 'Scientific & Academic', description: 'Complex scientific terms, hypotheses, and charts' },
  { value: 'Super Spy Stealth', description: 'Espionage jargon, secret bypasses, and infiltration tactics' },
  { value: 'Pro Gamer Speedrunner', description: 'Frame-perfect inputs, collision boxes, and APM analysis' },
  { value: 'Philosophical & Deep', description: 'Quantum mechanics, human consciousness, and existential mechanics' }
];

export function generateMockAIArticle(game: string, tone: string): Article {
  const timestamp = new Date().toLocaleDateString('en-US', { month: 'short', day: '2-digit', year: 'numeric' });
  const articleId = `art-custom-${Date.now()}`;

  let title = '';
  let content = '';

  if (tone === 'Scientific & Academic') {
    title = `A Quantitative Study on Modern ${game} Performance and Prefrontal Cortex Stimulation`;
    content = `### 1. Abstract and Methodology
This study evaluates high-resolution user interactions within the computational application *${game}*. By monitoring eye-tracking metrics and galvanic skin responses, our research group monitored cognitive load variations across variable speeds.

### 2. Key Hypotheses
* **Hypothesis Alpha:** Under exposure to intense gameplay in *${game}*, synaptic transmission within the occipital lobe scales non-linearly to register color hazards.
* **Correlative Result:** Microsecond adjustment of visual fields triggers an immediate increase in peripheral spatial visualization, allowing students to process complex diagrams in physical sciences faster.

### 3. Conclusion
Our empirical calculations assert that interacting with *${game}* for up to 15 minutes acts as a cognitive refresher, reducing baseline fatigue and optimizing cognitive processing speeds.`;
  } else if (tone === 'Super Spy Stealth') {
    title = `Infiltration Dossier: Maximizing ${game} Runtime in High-Monitoring Zones`;
    content = `### 1. Operational Reconnaissance
When running *${game}*, the primary threat landscape is the "Teacher Walkby" event (TWE). Standard response paths rely on alt-tab shortcuts, but advanced operators deploy hardware-level strategies for deep classroom stealth.

### 2. Tactical Mitigation Strategies
* **The Dual-Tabs Illusion:** Keep a document labeled "Advanced Trigonometric Integrals" open in an adjacent viewport.
* **Peripheral Awareness:** Calibrate your eyes to catch a teachers movement from 45 feet away.
* **Mechanical Silence:** Restrict key clicks to soft-press strokes so you do not announce your high actions per minute (APM) rate.

### 3. Mission Summary
Operating unblocked games is an exercise in absolute situational awareness. Maintain dynamic speed and perfect screen angling. Over and out.`;
  } else if (tone === 'Pro Gamer Speedrunner') {
    title = `Frame-Perfect Optimization in ${game}: Sub-pixel Alignments and Route Outlines`;
    content = `### 1. Glitches and Vector Angles
To achieve top-tier performance in *${game}*, casually playing is no longer viable. We must dive into collision box dimensions and frame-perfect ticks.

### 2. Speedrun Tricks Revealed
* **Buffer Swiping:** Pre-holding inputs allows you to trigger momentum updates on the very first accessible tick.
* **Visual Hitbox Deception:** The actual hitbox of your game character is usually 12% smaller than the sprite artwork indicates, allowing you to clip corners securely.
* **Rethinking Refresh Rates:** Locking the game engine to exactly 60Hz stabilizes the movement calculations, avoiding floating-point rounding bugs.

### 3. Setup Verdict
Combine lower resolution scales with static rendering to secure the ultimate latency advantage. Happy speedrunning!`;
  } else {
    // Philosophical
    title = `The Existential Void of ${game}: Finding Meaning in Infinite Geometry`;
    content = `### 1. The Endless Ascent
Why do we tilt and turn, stack blocks, or slide through endless tunnels in *${game}*? We search for sequence within absolute chaos, seeking structural harmony in a program built of simple silicon.

### 2. Metaphysical Mechanics
* **Infinite Loops:** The lack of a final winning screen turns *${game}* into a perfect digital metaphor for Sisyphus. It teaches us to love the roll of the ball and the assembly of binary rows.
* **Spatial Detachment:** Our focus blends into the pixels, detaching the mind from the immediate structural limits of the physics classroom.
* **Temporal Distortion:** Minutes melt into nanoseconds, pointing to the true malleability of human psychological perception.

### 3. Enlightenment Achieved
Enjoy *${game}* not for the score, but for the quiet void it creates inside the busy noise of the modern world.`;
  }

  return {
    id: articleId,
    title,
    subtitle: `Generated on-the-fly by Gemini-Pro Model • ${tone}`,
    content,
    date: timestamp,
    category: game,
    readTime: '2 min read',
    isCustomGenerated: true
  };
}
